const colors = [
  { code: '#e60000', name: 'dark red' },
  { code: '#ff9900', name: 'vivid orange' },
  { code: '#ffff00', name: 'bright yellow' },
  { code: '#008a00', name: 'vivid green' },
  { code: '#0066cc', name: 'vivid blue' },
  { code: '#9933ff', name: 'vivid purple' },
  { code: '#ffffff', name: 'white' },
  { code: '#facccc', name: 'light pink' },
  { code: '#ffebcc', name: 'light orange' },
  { code: '#ffffcc', name: 'light yellow' },
  { code: '#cce8cc', name: 'light green' },
  { code: '#cce0f5', name: 'light blue' },
  { code: '#ebd6ff', name: 'light purple' },
  { code: '#bbbbbb', name: 'gray' },
  { code: '#f06666', name: 'soft red' },
  { code: '#ffc266', name: 'soft orange' },
  { code: '#ffff66', name: 'soft yellow' },
  { code: '#66b966', name: 'soft green' },
  { code: '#66a3e0', name: 'soft blue' },
  { code: '#c285ff', name: 'soft purple' },
  { code: '#888888', name: 'medium gray' },
  { code: '#a10000', name: 'medium red' },
  { code: '#b26b00', name: 'medium orange' },
  { code: '#b2b200', name: 'medium yellow' },
  { code: '#006100', name: 'medium green' },
  { code: '#0047b2', name: 'medium blue' },
  { code: '#6b24b2', name: 'medium purple' },
  { code: '#444444', name: 'dark gray' },
  { code: '#5c0000', name: 'deep red' },
  { code: '#663d00', name: 'deep orange' },
  { code: '#666600', name: 'deep yellow' },
  { code: '#003700', name: 'deep green' },
  { code: '#002966', name: 'deep blue' },
  { code: '#3d1466', name: 'deep purple' },
  { code: '', name: 'black' },
];
export default colors;
